### ISSUE TITLE
getting an error while building the application.

### ISSUE THREAD

**Issue by shrujanus** [jamiejones85/ESP32-DASH#1]
Can someone please help me with this?
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/80990787/222016797-d740af4b-5aa5-4f6a-a569-c36faee8c872.png">

**Comment by jamiejones85** [comment]
Not enough information there, need the full error.

**Comment by shrujanus** [comment]
<img width="955" alt="image" src="https://user-images.githubusercontent.com/80990787/222136737-5f99f19b-e5c8-4ecc-ac74-5b0a10f36be9.png">
<img width="955" alt="image" src="https://user-images.githubusercontent.com/80990787/222136786-5fd3d6f4-7c59-411d-9b01-fca459646547.png">
I am using a esp32 dev board

**Comment by shrujanus** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/80990787/222138449-39887c6e-2d71-4af6-8ea3-1d9736641f3d.png">
 I was able to get that working by updating the async lib. Can you help me out with this error? How do I get connected?

**Comment by jamiejones85** [comment]
It looks like you're missing a SPIFFS partition, you also need to upload the Filesystem Image from the PlatformIO control.
The main loop isn't resetting the watchdog, so I assume it's not completing the setup function.

**Comment by shrujanus** [comment]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/80990787/222188719-15547e48-52e7-4d5a-b663-829880529384.png">

Thank you. I was able to upload the filesystem, and now I am getting this error. Do we have to replace the hostname with something else, or are we using ESP32 as softAP?

**Comment by jamiejones85** [comment]
It uses both, STA and AP. Connect to the AP it creates, navigate to 192.168.4.1/wifi

**Comment by shrujanus** [comment]
Thanks, it works now!!
